//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerAndGiftShop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FAGShopResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FAGShopResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowerAndGiftShop.App_LocalResources.FAGShopResources", typeof(FAGShopResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About orders.
        /// </summary>
        public static string AboutOrders {
            get {
                return ResourceManager.GetString("AboutOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000 Skopje.
        /// </summary>
        public static string addressCityData {
            get {
                return ResourceManager.GetString("addressCityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonia.
        /// </summary>
        public static string addressCountryData {
            get {
                return ResourceManager.GetString("addressCountryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sv. Kliment Ohridski 135.
        /// </summary>
        public static string addressStreetData {
            get {
                return ResourceManager.GetString("addressStreetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Flowers.
        /// </summary>
        public static string AllFlowers {
            get {
                return ResourceManager.GetString("AllFlowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Gifts.
        /// </summary>
        public static string AllGifts {
            get {
                return ResourceManager.GetString("AllGifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balloons.
        /// </summary>
        public static string Balloons {
            get {
                return ResourceManager.GetString("Balloons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouquets.
        /// </summary>
        public static string Bouquets {
            get {
                return ResourceManager.GetString("Bouquets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy All.
        /// </summary>
        public static string BuyAll {
            get {
                return ResourceManager.GetString("BuyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Order.
        /// </summary>
        public static string CancelOrder {
            get {
                return ResourceManager.GetString("CancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        public static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carniations.
        /// </summary>
        public static string Carniations {
            get {
                return ResourceManager.GetString("Carniations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas.
        /// </summary>
        public static string Christmas {
            get {
                return ResourceManager.GetString("Christmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Promotion.
        /// </summary>
        public static string CreatePromotion {
            get {
                return ResourceManager.GetString("CreatePromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer.
        /// </summary>
        public static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        public static string CustomerID {
            get {
                return ResourceManager.GetString("CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Ordered.
        /// </summary>
        public static string DateOrdered {
            get {
                return ResourceManager.GetString("DateOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date to be completed.
        /// </summary>
        public static string DateToBeCompleted {
            get {
                return ResourceManager.GetString("DateToBeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorations.
        /// </summary>
        public static string Decorations {
            get {
                return ResourceManager.GetString("Decorations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string deleteConfirm {
            get {
                return ResourceManager.GetString("deleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery address:.
        /// </summary>
        public static string DeliveryAddress {
            get {
                return ResourceManager.GetString("DeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free delivery for every order with payment at least 30 minutes after it is created!.
        /// </summary>
        public static string deliveryMessage1Data {
            get {
                return ResourceManager.GetString("deliveryMessage1Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to employee.
        /// </summary>
        public static string employee {
            get {
                return ResourceManager.GetString("employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Status.
        /// </summary>
        public static string FinishedStatus {
            get {
                return ResourceManager.GetString("FinishedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flower.
        /// </summary>
        public static string Flower {
            get {
                return ResourceManager.GetString("Flower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowers.
        /// </summary>
        public static string Flowers {
            get {
                return ResourceManager.GetString("Flowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Delivery.
        /// </summary>
        public static string FreeDelivery {
            get {
                return ResourceManager.GetString("FreeDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerbera.
        /// </summary>
        public static string Gerbera {
            get {
                return ResourceManager.GetString("Gerbera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gifts.
        /// </summary>
        public static string Gifts {
            get {
                return ResourceManager.GetString("Gifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Item Details.
        /// </summary>
        public static string GoToItemDetails {
            get {
                return ResourceManager.GetString("GoToItemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include delivery.
        /// </summary>
        public static string IncludeDelivery {
            get {
                return ResourceManager.GetString("IncludeDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Employee.
        /// </summary>
        public static string IsEmployee {
            get {
                return ResourceManager.GetString("IsEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        public static string ItemCode {
            get {
                return ResourceManager.GetString("ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Price.
        /// </summary>
        public static string ItemPrice {
            get {
                return ResourceManager.GetString("ItemPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        public static string ItemType {
            get {
                return ResourceManager.GetString("ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lilies.
        /// </summary>
        public static string Lilies {
            get {
                return ResourceManager.GetString("Lilies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More about delivery.
        /// </summary>
        public static string MoreAboutDelivery {
            get {
                return ResourceManager.GetString("MoreAboutDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Favorites.
        /// </summary>
        public static string MyFavorites {
            get {
                return ResourceManager.GetString("MyFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Orders.
        /// </summary>
        public static string MyOrders {
            get {
                return ResourceManager.GetString("MyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Shop Cart.
        /// </summary>
        public static string MyShopCart {
            get {
                return ResourceManager.GetString("MyShopCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of available pieces.
        /// </summary>
        public static string NumberOfAvailablePieces {
            get {
                return ResourceManager.GetString("NumberOfAvailablePieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        public static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderPackages.
        /// </summary>
        public static string OrderPackages {
            get {
                return ResourceManager.GetString("OrderPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor Party.
        /// </summary>
        public static string OutdoorParty {
            get {
                return ResourceManager.GetString("OutdoorParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phones.
        /// </summary>
        public static string Phones {
            get {
                return ResourceManager.GetString("Phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month you can enjoy at more than 50 products included in Valentine&apos;s day promotion..
        /// </summary>
        public static string promotionMessage1Data {
            get {
                return ResourceManager.GetString("promotionMessage1Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay tuned &apos;cause many new promotions are coming up - new month, same place!.
        /// </summary>
        public static string promotionMessage2Data {
            get {
                return ResourceManager.GetString("promotionMessage2Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotions.
        /// </summary>
        public static string Promotions {
            get {
                return ResourceManager.GetString("Promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion up to.
        /// </summary>
        public static string PromotionUpTo {
            get {
                return ResourceManager.GetString("PromotionUpTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register account.
        /// </summary>
        public static string RegisterAccount {
            get {
                return ResourceManager.GetString("RegisterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still not our member? Register your account for FREE and use our great services!.
        /// </summary>
        public static string registerMessage1Data {
            get {
                return ResourceManager.GetString("registerMessage1Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string RegisteRNewUser {
            get {
                return ResourceManager.GetString("RegisteRNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register NOW.
        /// </summary>
        public static string RegisterNow {
            get {
                return ResourceManager.GetString("RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Order.
        /// </summary>
        public static string RejectOrder {
            get {
                return ResourceManager.GetString("RejectOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Favorites.
        /// </summary>
        public static string RemoveFromFavorites {
            get {
                return ResourceManager.GetString("RemoveFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Shop Cart.
        /// </summary>
        public static string RemoveFromShopCart {
            get {
                return ResourceManager.GetString("RemoveFromShopCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roses.
        /// </summary>
        public static string Roses {
            get {
                return ResourceManager.GetString("Roses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        public static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select quantity.
        /// </summary>
        public static string SelectQuantity {
            get {
                return ResourceManager.GetString("SelectQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set As Completed.
        /// </summary>
        public static string SetAsCompleted {
            get {
                return ResourceManager.GetString("SetAsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopCart.
        /// </summary>
        public static string ShopCart {
            get {
                return ResourceManager.GetString("ShopCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flower &amp; Gift Shop Viviano Logo.
        /// </summary>
        public static string shopNameData {
            get {
                return ResourceManager.GetString("shopNameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweets.
        /// </summary>
        public static string Sweets {
            get {
                return ResourceManager.GetString("Sweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teddy Bears.
        /// </summary>
        public static string TeddyBears {
            get {
                return ResourceManager.GetString("TeddyBears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in.
        /// </summary>
        public static string UseLocalAccountLogIn {
            get {
                return ResourceManager.GetString("UseLocalAccountLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View current promotion.
        /// </summary>
        public static string ViewCurrentPromotion {
            get {
                return ResourceManager.GetString("ViewCurrentPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are here.
        /// </summary>
        public static string WeAreHere {
            get {
                return ResourceManager.GetString("WeAreHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding.
        /// </summary>
        public static string Wedding {
            get {
                return ResourceManager.GetString("Wedding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wines.
        /// </summary>
        public static string Wines {
            get {
                return ResourceManager.GetString("Wines", resourceCulture);
            }
        }
    }
}
