// <auto-generated />
namespace FlowerAndGiftShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Added_ItemType_ItemID_Price_OrderModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_ItemType_ItemID_Price_OrderModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201412111718063_Added_ItemType_ItemID_Price_OrderModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
